//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BookInventories = new HashSet<BookInventory>();
            this.WantLists = new HashSet<WantList>();
        }
    
        public int Id { get; set; }
        public int Issue { get; set; }
        public bool IsSpecialCover { get; set; }
        public int SeriesId { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<BookInventory> BookInventories { get; set; }
        public virtual ICollection<WantList> WantLists { get; set; }
        public virtual Series Series { get; set; }
    }
}
