//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.BookInventories = new HashSet<BookInventory>();
            this.Location1 = new HashSet<Location>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> NextLocationId { get; set; }
    
        public virtual ICollection<BookInventory> BookInventories { get; set; }
        public virtual ICollection<Location> Location1 { get; set; }
        public virtual Location Location2 { get; set; }
    }
}
