//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class WantList
    {
        public int Id { get; set; }
        public Nullable<int> BookId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> WantListStatusId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual WantListStatu WantListStatu { get; set; }
    }
}
